---
name: Proofread
on: [push]

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
  proofread:
    name: Proofread
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: place-labs/orthograph-err@master
